# Generated by Django 3.0.5 on 2020-07-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.TextField()),
                ('CategoryDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionTitle', models.TextField()),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.TextField()),
                ('Categories', models.ManyToManyField(to='question.Category')),
            ],
        ),
    ]
