# Generated by Django 3.0.5 on 2020-07-24 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=150, null=True)),
                ('City', models.CharField(max_length=150)),
                ('District', models.CharField(max_length=150)),
                ('Pincode', models.CharField(max_length=150)),
                ('Qualification', models.CharField(max_length=150)),
                ('UserId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
